package com.github.countrycode.reverse;

import static org.junit.Assert.assertEquals;

import java.util.Collection;

import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import com.google.common.collect.ImmutableList;

@RunWith(Parameterized.class)
public class ReverseCountryCodeTest {

    private static ReverseCountryCode lookup;

    private final double lat;
    private final double lon;
    private final String code;

    public ReverseCountryCodeTest(double lat, double lon, String code) {
        this.lat = lat;
        this.lon = lon;
        this.code = code;
    }

    @BeforeClass
    public static void setup() {
        lookup = new ReverseCountryCode();
    }

    @Test
    public void test() {
        assertEquals(code, lookup.getCountryCode(lat, lon));
    }

    @Parameters(name = "{0},{1} = {2}")
    public static Collection<Object[]> data() {
        return ImmutableList.<Object[]> builder()
                .add(new Object[] { 36.433333, 28.216667, "GR" })
                .add(new Object[] { 36.7283, 27.6869, "TR" })
                .add(new Object[] { 52.7, 13.8, "DE" })
                .add(new Object[] { -88.0, 8.9, "AQ" })
                .add(new Object[] { 61.7, -5.5, null })
                .add(new Object[] { -14.5, 135.2, "AU" })
                .add(new Object[] { -68.1, -112.2, null })
                .add(new Object[] { -9.2, -1.8, null })
                .add(new Object[] { -51.5, 97.2, null })
                .add(new Object[] { -72.0, -39.9, null })
                .add(new Object[] { -3.4, 67.5, null })
                .add(new Object[] { -5.1, -138.2, null })
                .add(new Object[] { -77.1, 131.7, "AQ" })
                .add(new Object[] { -23.4, 163.2, null })
                .add(new Object[] { -58.0, 165.0, null })
                .add(new Object[] { -89.2, -172.6, "AQ" })
                .add(new Object[] { 7.8, -124.7, null })
                .add(new Object[] { -66.1, 17.4, null })
                .add(new Object[] { -52.3, -124.3, null })
                .add(new Object[] { 2.4, 45.8, "SO" })
                .add(new Object[] { 45.2, 169.1, null })
                .add(new Object[] { 62.6, 179.7, null })
                .add(new Object[] { -1.6, 148.7, null })
                .add(new Object[] { 89.8, -168.7, null })
                .add(new Object[] { 60.6, -38.9, null })
                .add(new Object[] { 23.0, -66.1, null })
                .add(new Object[] { 21.3, -40.4, null })
                .add(new Object[] { 79.9, 107.4, null })
                .add(new Object[] { 32.7, 141.6, null })
                .add(new Object[] { 19.5, -104.0, "MX" })
                .add(new Object[] { 34.5, 54.6, "IR" })
                .add(new Object[] { 68.5, -160.9, "US" })
                .add(new Object[] { 74.9, -141.4, null })
                .add(new Object[] { -1.1, -38.5, null })
                .add(new Object[] { -14.8, 38.6, "MZ" })
                .add(new Object[] { -59.8, 35.1, null })
                .add(new Object[] { 22.0, -83.3, null })
                .add(new Object[] { 72.5, 100.8, "RU" })
                .add(new Object[] { -67.8, -72.7, null })
                .add(new Object[] { 8.5, 156.9, null })
                .add(new Object[] { 47.0, -41.0, null })
                .add(new Object[] { 2.2, 123.7, null })
                .add(new Object[] { 18.5, -48.9, null })
                .add(new Object[] { 13.3, -67.2, null })
                .add(new Object[] { -37.0, 116.6, null })
                .add(new Object[] { -14.2, 90.6, null })
                .add(new Object[] { -20.7, 173.9, null })
                .add(new Object[] { 4.3, -92.6, null })
                .add(new Object[] { 16.6, 144.0, null })
                .add(new Object[] { 49.7, 104.4, "MN" })
                .add(new Object[] { -55.5, -31.0, null })
                .add(new Object[] { -75.7, 19.5, "AQ" })
                .add(new Object[] { -76.4, -30.5, null })
                .add(new Object[] { 81.0, -68.8, "CA" })
                .add(new Object[] { 15.1, -64.8, null })
                .add(new Object[] { 52.5, 65.8, "KZ" })
                .add(new Object[] { -73.4, 159.0, "AQ" })
                .add(new Object[] { 34.6, -70.8, null })
                .add(new Object[] { 23.3, 9.8, "DZ" })
                .add(new Object[] { -40.2, 41.7, null })
                .add(new Object[] { 87.3, 10.4, null })
                .add(new Object[] { 40.4, -134.1, null })
                .add(new Object[] { -50.9, -83.5, null })
                .add(new Object[] { -26.3, 77.1, null })
                .add(new Object[] { -77.2, 126.7, "AQ" })
                .add(new Object[] { -39.4, -175.5, null })
                .add(new Object[] { 77.7, 11.0, null })
                .add(new Object[] { 46.2, -86.3, "US" })
                .add(new Object[] { 37.3, 146.7, null })
                .add(new Object[] { 8.5, -122.8, null })
                .add(new Object[] { 65.3, 75.8, "RU" })
                .add(new Object[] { -58.5, -155.8, null })
                .add(new Object[] { 52.1, 7.3, "DE" })
                .add(new Object[] { -83.6, -81.9, "AQ" })
                .add(new Object[] { -56.0, -92.4, null })
                .add(new Object[] { 16.1, 146.7, null })
                .add(new Object[] { 65.4, -169.3, null })
                .add(new Object[] { -28.9, 8.1, null })
                .add(new Object[] { -77.8, -64.8, null })
                .add(new Object[] { -40.5, -26.1, null })
                .add(new Object[] { -83.8, -139.3, "AQ" })
                .add(new Object[] { -78.2, 39.5, "AQ" })
                .add(new Object[] { -74.2, -74.9, "AQ" })
                .add(new Object[] { -4.3, -168.7, null })
                .add(new Object[] { -84.9, 70.7, "AQ" })
                .add(new Object[] { -41.1, 35.8, null })
                .add(new Object[] { -6.5, 87.5, null })
                .add(new Object[] { 56.4, 54.7, "RU" })
                .add(new Object[] { 7.6, -107.2, null })
                .add(new Object[] { -19.9, 32.7, "ZW" })
                .add(new Object[] { 54.9, 169.7, null })
                .add(new Object[] { 44.3, 95.2, "MN" })
                .add(new Object[] { -0.6, -59.4, "BR" })
                .add(new Object[] { 66.5, -136.8, "CA" })
                .add(new Object[] { -51.9, -119.9, null })
                .add(new Object[] { 21.7, -26.1, null })
                .add(new Object[] { -87.8, -106.9, "AQ" })
                .add(new Object[] { -85.0, -175.9, "AQ" })
                .add(new Object[] { -85.3, 94.9, "AQ" })
                .add(new Object[] { 79.3, -77.5, "CA" })
                .add(new Object[] { 66.0, -1.0, null })
                .add(new Object[] { 32.0, 22.4, "LY" })
                .add(new Object[] { 65.2, -5.7, null })
                .add(new Object[] { 55.8, -11.4, null })
                .add(new Object[] { 33.1, 6.8, "DZ" })
                .add(new Object[] { 53.3, 36.2, "RU" })
                .add(new Object[] { 79.8, 1.0, null })
                .add(new Object[] { 60.5, 4.6, null })
                .add(new Object[] { 63.5, -13.9, null })
                .add(new Object[] { 46.6, 15.8, "SI" })
                .add(new Object[] { 63.4, 11.1, "NO" })
                .add(new Object[] { 28.4, -21.3, null })
                .add(new Object[] { 29.9, 30.0, "EG" })
                .add(new Object[] { 54.5, -9.2, null })
                .add(new Object[] { 76.5, 8.3, null })
                .add(new Object[] { 37.4, -22.0, null })
                .add(new Object[] { 62.8, -16.9, null })
                .add(new Object[] { 45.2, 26.2, "RO" })
                .add(new Object[] { 48.8, -4.3, null })
                .add(new Object[] { 73.4, 5.3, null })
                .add(new Object[] { 46.7, 152.9, null })
                .add(new Object[] { 69.1, 179.8, null })
                .add(new Object[] { 41.7, 123.1, "CN" })
                .add(new Object[] { 7.6, -5.2, "CI" })
                .add(new Object[] { 27.5, 9.2, "DZ" })
                .add(new Object[] { 66.9, 125.0, "RU" })
                .add(new Object[] { 6.0, 38.9, "ET" })
                .add(new Object[] { 60.3, 116.7, "RU" })
                .add(new Object[] { 80.6, 32.5, null })
                .add(new Object[] { -7.7, 146.3, "PG" })
                .add(new Object[] { 16.9, 128.1, null })
                .add(new Object[] { 57.2, 101.1, "RU" })
                .add(new Object[] { 10.0, 4.1, "NG" })
                .add(new Object[] { 62.3, 67.8, "RU" })
                .add(new Object[] { 66.7, 91.2, "RU" })
                .add(new Object[] { -11.4, 136.4, null })
                .add(new Object[] { 5.3, 76.2, null })
                .add(new Object[] { 58.7, 155.8, null })
                .add(new Object[] { -8.0, 25.5, "CD" })
                .add(new Object[] { -8.5, 137.7, null })
                .add(new Object[] { -27.8, -12.2, null })
                .add(new Object[] { 27.3, 2.1, "DZ" })
                .add(new Object[] { -5.0, 53.2, null })
                .add(new Object[] { 17.7, 23.4, "TD" })
                .add(new Object[] { -36.3, 49.9, null })
                .add(new Object[] { -34.0, 15.9, null })
                .add(new Object[] { -41.1, 6.3, null })
                .add(new Object[] { 34.3, -21.7, null })
                .add(new Object[] { -14.9, 54.8, null })
                .add(new Object[] { 10.5, -11.7, "GN" })
                .add(new Object[] { -34.6, 25.4, null })
                .add(new Object[] { -9.9, 53.0, null })
                .add(new Object[] { 2.3, 33.5, "UG" })
                .add(new Object[] { 25.3, 53.7, null })
                .add(new Object[] { 20.5, 59.2, null })
                .add(new Object[] { 15.4, 29.9, "SD" })
                .add(new Object[] { 1.6, -5.7, null })
                .add(new Object[] { 32.5, 0.3, "DZ" })
                .add(new Object[] { -22.6, 25.7, "BW" })
                .add(new Object[] { -5.6, 58.1, null })
                .add(new Object[] { 82.1, -100.8, null })
                .add(new Object[] { 39.4, -162.8, null })
                .add(new Object[] { 69.1, -109.1, "CA" })
                .add(new Object[] { 56.0, -122.3, "CA" })
                .add(new Object[] { 24.8, -54.4, null })
                .add(new Object[] { 57.6, -113.8, "CA" })
                .add(new Object[] { 80.3, -128.1, null })
                .add(new Object[] { 35.0, -82.0, "US" })
                .add(new Object[] { 65.7, -86.9, "CA" })
                .add(new Object[] { 37.2, -90.5, "US" })
                .add(new Object[] { 14.0, -78.9, null })
                .add(new Object[] { 13.4, -160.3, null })
                .add(new Object[] { 26.3, -104.9, "MX" })
                .add(new Object[] { 12.8, -129.0, null })
                .add(new Object[] { 71.5, -116.6, "CA" })
                .add(new Object[] { 37.3, -88.1, "US" })
                .add(new Object[] { 51.0, -124.5, "CA" })
                .add(new Object[] { 57.4, -84.9, null })
                .add(new Object[] { 77.9, -140.4, null })
                .add(new Object[] { 76.2, -111.5, null })
                .add(new Object[] { -14.1, -67.7, "BO" })
                .add(new Object[] { -20.2, -65.8, "BO" })
                .add(new Object[] { 10.5, -75.6, null })
                .add(new Object[] { -15.9, -97.9, null })
                .add(new Object[] { -19.1, -83.5, null })
                .add(new Object[] { 1.1, -76.1, "CO" })
                .add(new Object[] { 7.8, -68.1, "VE" })
                .add(new Object[] { -19.7, -63.2, "BO" })
                .add(new Object[] { 6.1, -97.7, null })
                .add(new Object[] { -20.4, -68.3, "BO" })
                .add(new Object[] { -9.3, -100.0, null })
                .add(new Object[] { -6.7, -97.0, null })
                .add(new Object[] { -9.6, -86.0, null })
                .add(new Object[] { -0.1, -97.1, null })
                .add(new Object[] { -2.1, -103.4, null })
                .add(new Object[] { 2.7, -71.3, "CO" })
                .add(new Object[] { -10.8, -94.9, null })
                .add(new Object[] { -21.1, -91.5, null })
                .add(new Object[] { -8.3, -88.8, null })
                .add(new Object[] { -9.3, -61.2, "BR" })
                .build();
    }

}
